const styles = [
  {
    name: "High Fidelity",
    description: "Detailed cartoon portraits",
  },
  {
    name: "Stylized",
    description: "Cute blob characters",
  },
  {
    name: "Abstract",
    description: "Animal & object mashups",
  },
  {
    name: "Chibi",
    description: "Big head, tiny body",
  },
  {
    name: "Minimalist",
    description: "Simple line art style",
  },
];

export function StyleGallery() {
  return (
    <section id="styles" className="py-24 md:py-32">
      <div className="text-center mb-16">
        <span className="text-primary font-medium text-sm uppercase tracking-widest">
          Art Styles
        </span>
        <h2 className="mt-4 text-3xl md:text-4xl font-bold text-foreground text-balance">
          5 unique styles to choose from
        </h2>
        <p className="mt-4 text-muted-foreground max-w-lg mx-auto text-pretty">
          Each style brings out a different personality. Pick one that matches yours.
        </p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4 md:gap-6">
        {styles.map((style, index) => (
          <div key={style.name} className="group">
            <div className="bg-secondary aspect-square rounded-2xl flex items-center justify-center border border-border">
              <div className="bg-muted size-20 md:size-24 rounded-2xl flex items-center justify-center">
                <span className="text-2xl md:text-3xl font-bold text-muted-foreground/30">
                  {index + 1}
                </span>
              </div>
            </div>
            <div className="mt-3 text-center">
              <h3 className="font-semibold text-foreground text-sm">
                {style.name}
              </h3>
              <p className="text-xs text-muted-foreground mt-0.5">
                {style.description}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* Sample stickers showcase */}
      <div className="mt-16 text-center">
        <p className="text-sm text-muted-foreground mb-6 text-pretty">
          Example stickers generated by AI - yours will feature your face
        </p>
        <div className="flex justify-center gap-3 flex-wrap">
          {[...Array(6)].map((_, i) => (
            <div
              key={i}
              className="size-16 md:size-20 rounded-xl bg-secondary border border-border flex items-center justify-center"
            >
              <div className="size-8 md:size-10 rounded-full bg-muted" />
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
